#!/usr/bin/env python3
"""Deploy generated static site to a dedicated public repo under GITHUB_ORG."""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE_DIR = ROOT / "site"
LEADS_FILE = ROOT / "data" / "leads.json"

API_VERSION = "2022-11-28"


def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    return re.sub(r"[\s_-]+", "-", text).strip("-") or "site"


def repo_slug_for_lead(lead: dict) -> str:
    parts = [slugify(lead.get("name") or "business")]
    city = lead.get("city") or ""
    if city:
        parts.append(slugify(city.split(",")[0]))
    phone = re.sub(r"\D", "", lead.get("phone") or "")
    if phone:
        parts.append(phone[-4:])
    slug = "-".join(p for p in parts if p)
    return slug[:90]


def load_lead() -> dict:
    leads = json.loads(LEADS_FILE.read_text(encoding="utf-8"))
    index = int(os.environ.get("LEAD_INDEX", "0"))
    if index < 0 or index >= len(leads):
        raise SystemExit(f"LEAD_INDEX {index} out of range (0-{len(leads) - 1})")
    return leads[index]


def github_request(method: str, path: str, token: str, payload: dict | None = None) -> tuple[int, dict | list | None]:
    url = f"https://api.github.com{path}"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": API_VERSION,
    }
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    if data is not None:
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            raw = resp.read().decode("utf-8")
            return resp.status, json.loads(raw) if raw else None
    except urllib.error.HTTPError as exc:
        raw = exc.read().decode("utf-8", errors="replace")
        try:
            body = json.loads(raw) if raw else None
        except json.JSONDecodeError:
            body = {"message": raw}
        return exc.code, body


def ensure_org_exists(org: str, token: str) -> None:
    status, body = github_request("GET", f"/orgs/{org}", token)
    if status == 200:
        return
    message = (body or {}).get("message", "unknown error") if isinstance(body, dict) else "unknown error"
    raise SystemExit(
        f"GitHub org '{org}' not found or token lacks access ({status}: {message}).\n"
        f"Create it at https://github.com/organizations/plan?organization_name={org}\n"
        "Then re-run the pipeline. ORG_DEPLOY_TOKEN must be from an org owner with repo create rights."
    )


def niche_topic(lead: dict) -> str:
    raw = (lead.get("niche_id") or lead.get("niche") or "local-business").lower()
    topic = re.sub(r"[^a-z0-9-]", "-", raw.replace("_", "-"))
    topic = re.sub(r"-+", "-", topic).strip("-")
    return topic[:35] or "local-business"


def set_repo_topics(org: str, repo: str, token: str, lead: dict) -> None:
    topics = sorted({"web-auto", niche_topic(lead)})
    status, body = github_request(
        "PUT",
        f"/repos/{org}/{repo}/topics",
        token,
        {"names": topics},
    )
    if status not in {200, 204}:
        message = (body or {}).get("message", body) if isinstance(body, dict) else body
        print(f"Warning: could not set repo topics ({status}): {message}")
    else:
        print(f"Topics set on {org}/{repo}: {', '.join(topics)}")


def ensure_repo(org: str, repo: str, token: str, lead: dict) -> None:
    status, _ = github_request("GET", f"/repos/{org}/{repo}", token)
    if status == 200:
        return
    niche = lead.get("niche") or lead.get("category") or "Local business"
    status, body = github_request(
        "POST",
        f"/orgs/{org}/repos",
        token,
        {
            "name": repo,
            "private": False,
            "auto_init": True,
            "description": f"{niche} lead site — generated by web-auto",
            "has_issues": False,
            "has_projects": False,
            "has_wiki": False,
        },
    )
    if status not in {201, 202}:
        message = (body or {}).get("message", body) if isinstance(body, dict) else body
        raise SystemExit(f"Failed to create repo {org}/{repo}: {status} {message}")
    time.sleep(3)


def git_push_site(org: str, repo: str, token: str, site_dir: Path) -> None:
    if not site_dir.is_dir() or not any(site_dir.iterdir()):
        raise SystemExit(f"Site directory is empty: {site_dir}")

    remote = f"https://x-access-token:{token}@github.com/{org}/{repo}.git"
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp) / "repo"
        clone = subprocess.run(
            ["git", "clone", "--depth", "1", remote, str(work)],
            capture_output=True,
            text=True,
        )
        if clone.returncode != 0:
            raise SystemExit(f"git clone failed: {clone.stderr or clone.stdout}")

        for child in work.iterdir():
            if child.name == ".git":
                continue
            if child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink()

        for item in site_dir.iterdir():
            dest = work / item.name
            if item.is_dir():
                shutil.copytree(item, dest)
            else:
                shutil.copy2(item, dest)

        subprocess.run(["git", "config", "user.email", "web-auto@users.noreply.github.com"], cwd=work, check=True)
        subprocess.run(["git", "config", "user.name", "web-auto"], cwd=work, check=True)
        subprocess.run(["git", "add", "-A"], cwd=work, check=True)
        status = subprocess.run(["git", "status", "--porcelain"], cwd=work, capture_output=True, text=True, check=True)
        if not status.stdout.strip():
            print("No file changes to deploy")
        else:
            subprocess.run(["git", "commit", "-m", "Deploy lead site"], cwd=work, check=True)
            push = subprocess.run(["git", "push", "origin", "HEAD:main"], cwd=work, capture_output=True, text=True)
            if push.returncode != 0:
                raise SystemExit(f"git push failed: {push.stderr or push.stdout}")


def enable_pages(org: str, repo: str, token: str) -> str:
    status, pages = github_request("GET", f"/repos/{org}/{repo}/pages", token)
    if status == 200 and isinstance(pages, dict):
        return pages.get("html_url") or f"https://{org}.github.io/{repo}/"

    status, body = github_request(
        "POST",
        f"/repos/{org}/{repo}/pages",
        token,
        {"build_type": "legacy", "source": {"branch": "main", "path": "/"}},
    )
    if status not in {201, 202, 409}:
        message = (body or {}).get("message", body) if isinstance(body, dict) else body
        raise SystemExit(f"Failed to enable Pages on {org}/{repo}: {status} {message}")

    for _ in range(12):
        status, pages = github_request("GET", f"/repos/{org}/{repo}/pages", token)
        if status == 200 and isinstance(pages, dict) and pages.get("html_url"):
            return pages["html_url"]
        time.sleep(5)

    return f"https://{org}.github.io/{repo}/"


def write_github_output(live_url: str, repo_slug: str) -> None:
    output_path = os.environ.get("GITHUB_OUTPUT")
    if output_path:
        with open(output_path, "a", encoding="utf-8") as fh:
            fh.write(f"live_url={live_url}\n")
            fh.write(f"repo_slug={repo_slug}\n")
    print(f"LIVE_URL={live_url}")
    print(f"REPO_SLUG={repo_slug}")


def main() -> None:
    org = os.environ.get("DEPLOY_ORG", os.environ.get("GITHUB_ORG", "kem-llc"))
    token = os.environ.get("ORG_DEPLOY_TOKEN") or os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if not token:
        raise SystemExit("ORG_DEPLOY_TOKEN (or GH_TOKEN) is not set")

    lead = load_lead()
    repo_slug = os.environ.get("DEPLOY_REPO") or repo_slug_for_lead(lead)
    print(f"Deploying {lead['name']} → {org}/{repo_slug}")

    ensure_org_exists(org, token)
    ensure_repo(org, repo_slug, token, lead)
    set_repo_topics(org, repo_slug, token, lead)
    git_push_site(org, repo_slug, token, SITE_DIR)
    live_url = enable_pages(org, repo_slug, token)
    if not live_url.endswith("/"):
        live_url += "/"

    write_github_output(live_url, repo_slug)
    print(f"Deployed to {live_url}")


if __name__ == "__main__":
    main()
